[package]
name = "tiktoken_ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
tiktoken-rs = "0.6.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
debug = false
